name: benchmark-on-command

on:
  issue_comment:
    types: [created]

jobs:
  on-master:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install --ignore-scripts
    - uses: Eomm/action-journalist@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        keywords: '["$run-benchmark"]'
        command: npm run benchmark

  on-issue:
    needs: on-master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install --ignore-scripts
    - uses: Eomm/action-journalist@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        keywords: '["$run-benchmark"]'
        command: npm run benchmark
